### ISSUE TITLE
Some Base64 encoded content without padding fails to be decoded

### ISSUE THREAD

**Issue by bartoszj** [furikake/sublime-codec#16]
Hello,

Some Base64 content without padding like `eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ` is not able to decode. Such data can be decoded: `eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ==`.

In the console I'm getting those messages:
```
Codec: fix base32 padding? False
Codec: fix base64 padding? False
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1488, in run_
    return self.run(edit, **args)
  File "/Users/abc/Library/Application Support/Sublime Text 3/Installed Packages/Codec.sublime-package/sublime_codec.py", line 78, in run
  File "/Users/abc/Library/Application Support/Sublime Text 3/Installed Packages/Codec.sublime-package/codec_base64.py", line 10, in b64decode
  File "./python3.3/base64.py", line 91, in b64decode
binascii.Error: Incorrect padding
```

**Comment by furikake** [comment]
Try adding the following to your config.
```
{
	"base64_fix_padding": true,
}
```

<img width="793" alt="sublime-codec-issue-16" src="https://user-images.githubusercontent.com/304671/121642167-7e408580-cad3-11eb-8e80-defccb6b3f60.png">

**Comment by bartoszj** [comment]
It works 😻. Thanks!
